# Generated by Django 5.1.4 on 2024-12-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pereval',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pereval.level'),
            preserve_default=False,
        ),
    ]
